version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=docker
      - DATABASE_URL=postgresql://farmadmin:Test123456789@farmhealth-database.postgres.database.azure.com:5432/postgres
      - PREDICTION_SERVICE_URL=http://52.156.253.109:5001

  python-server:
    build:
      context: ./python-server
    ports:
      - "5001:5001"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend